### ISSUE TITLE
Routable label should be "namespaced"

### ISSUE THREAD

**Issue by krancour** [deis/router#105]
Currently, the router finds "routable" apps by querying the k8s API for services with the label `routable: "true"`.

Ideally, these labels should probably change to `router.deis.io/routable: "true"`

cc @helgi: Workflow would need a complementary change.

**Comment by helgi** [comment]
That's fine but then you are moving into a config map / annotations instead of it being a label selector, which the k8s API has a much easier time to query against.

Don't think JSONPath is part of the API and only kubectl. If that was around we could do many more powerful things on random things

**Comment by krancour** [comment]
@helgi I wasn't proposing that it no longer be a label.  Labels definitely make for more efficient queries.  Do you know something I don't?  Like, perhaps, would `router.deis.io/routable` be an invalid label?  I need to check.

**Comment by helgi** [comment]
I have to look again but labels are DNS labels iirc, dots not are allowed in that case. It may be considered a subdomain label, which changes the game :)

**Comment by helgi** [comment]
Is the primary reasoning for this to be more identifiable as to what `routable` is and for who it is?

**Comment by krancour** [comment]
Yes.  We've done the same for annotations.  It seems we should do so here as well for consistency.

**Comment by helgi** [comment]
Part of me feels it's cruft and could get us into some odd scenarios down the line but at the same time it make sense
