### ISSUE TITLE
Add CI using travis

### ISSUE THREAD

**Issue by krancour** [deis/router#11]

**Comment by mboersma** [comment]
You might want to look at the quick-and-dirty approach I took in deis/etcd#11. (It's a pain already trying to keep this infrastructure synced up between the multiple projects, but I guess for now making an effort toward standardization is the best we can do.)

**Comment by krancour** [comment]
Yuo.  Already noticed that PR and was planning to model it after that... but first I need something to test.  :)

**Comment by krancour** [comment]
Closed by #15
