### ISSUE TITLE
Proposal: Configuration extensions

### ISSUE THREAD

**Issue by krancour** [deis/router#111]
Replaces #36 

Router is _very_ configurable.  Many of these configuration options, however, are really, at their core, _nginx_ configuration options.  Try as I might, it's very difficult to hide that fact, as many of the options exposed may not even have an analog in a hypothetical, alternative implementation (based on HAProxy, for instance).  Although an alternative implementation is only hypothetical at the moment, it's very likely to happen sooner or later, even if only within the community.

To that end, I would like to propose a modest re-organization of the router's configuration options _and_ the accompanying documentation to promote a clear separation between configuration options that are "spec" and therefore non-negotiable and a secondary class of configuration options that are "extensions;" that is to say-- implementation specific.

I would propose that this is to be achieved through a re-namespacing of all configuration options and careful re-organization of the configuration documentation.

By way of example, consider the following configuration options that can be set via annotations on the router's replication controller:

* router.deis.io/workerProcesses
* router.deis.io/workerConnections
* router.deis.io/serverNameHashMaxSize
* router.deis.io/gzip.disable
* (And many others)

These could be renamed as follows:

* router.deis.io/nginx.workerProcesses
* router.deis.io/nginx.workerConnections
* router.deis.io/nginx.serverNameHashMaxSize
* router.deis.io/nginx.gzip.disable

Again by example, certain other annotations on the router's replication controller, such as the following, may not initially appear to be implementation-specific:

* router.deis.io/defaultDomain

That is highly-speculative, however, because it's conceivable that other implementations might not _need_ such information.  (Even the current implementation considers it optional.)  Taking this into consideration, there's no harm in also re-namespacing annotations such as these to:

* router.deis.io/nginx.defaultDomain

In contrast to all of the above, all annotations that form the contract between the router and workflow should be considered "spec" and non-negotiable.  Any alternative implementation of the router would have to respect these.  These encompass all the annotations that workflow sets on "routable" application services, such as:

* router.deis.io/domains
* router.deis.io/certificates
* router.deis.io/whitelist

For improved clarity, these could also be re-namespaced as well:

* router.deis.io/app.domains
* router.deis.io/app.certificates
* router.deis.io/app.whitelist

In the end, I believe, with the right documentation, it becomes clear that the "app" annotations are spec and non-negotiable, whilst the "nginx" annotations are specific to the current router implementation.

I'd like to invite questions or concerns re: this approach.

**Comment by technosophos** [comment]
This proposal seems like a sane way to proceed in a way that is future-proof. I don't have any reservations with the idea, and the only implementation detail that concerns me is the one that is already raised: We have to be careful about what we claim is "global".

I like the idea that we could override certain "global" params with implementation specific ones, so in the case where a certain implementation might provide some useful functionality in addition to base functionality, we could support that.

For example, imagine the case where a specific implementation allowed better regular expressions (rather than POSIX glob style). We could simply have:

```
router.deis.io/domain=*.example.com
router.deis.io/nginx.domain=[a-zA-Z0-9-]+.example.com
```

The above is a contrived example -- I'm not proposing something specific, just the idea that in some cases we could allow namespaced params to override default global params.

Regardless, I like this idea a lot and think we should do it pre-Beta.

**Comment by krancour** [comment]
@technosophos thanks for the feedback.  Would you be opposed / how much would you be opposed if I opted for simplicity here?  I think the notion of "global" (or "core" as I might like to call it) configuration that can be overridden with implementation specific things adds a lot of complexity and not a lot of value.

My reasoning is that first, designating _any_ config keys apart from those on routable services (the touchpoint between router and workflow) that implementations _must_ honor (if not overridden) raises the barrier to entry for anyone wishing to implement a custom router.

Second, but possibly more significant, I'm not sure what the added complexity of such a scheme buys us.  The k8s annotations on the router rc _only_ affect the router.  They don't affect the behavior of any other Deis components.  That means it's entirely reasonable for an alternate implementation to expose a _wildly_ different set of options, which could even, if they so chose, use wildly different keys for the annotations... but it doesn't matter so long as each implementation adequately documents "here's how you configure _me_."  Hell... if an alternate implementation didn't care about reconfiguring on the fly without any downtime, they could even rely on environment variables for configuration moreso than annotations-- and it would be no skin off our backs as long as they did honor the small handful of annotations on the routable services (the "spec").

I suppose that in the end, what I'm going for here is tremendously subtle.  The scheme I've suggested isn't anything enforceable... nor, as I said, do I think we should care.  My only goal is to make it clear to users of _our_ router implementation that most of the config they are dealing with is specific to the implementation.

Does this make any sense or is the cold medicine catching up with me?

**Comment by technosophos** [comment]
Actually, what I like about your proposal is that you can start without it and add inheritance at some point later if that makes sense. I'm :100: behind simple.

**Comment by krancour** [comment]
Thanks!

**Comment by helgi** [comment]
This starts getting into the world of people needing to know what lower level implementation the router has and configurable accordingly. While not bad per se (they should always know) it isn't the cleanest UX. I've done solutions before that worked for Varnish and HAProxy and I know from experience that keeping the total global configuration "generic" is not easy.

What you have proposed is probably the easiest however. I don't have any particular suggestions for it right now beyond "go for it".

However lets not add `app` namespace there

**Comment by krancour** [comment]
> However lets not add app namespace there

Reasonable.

**Comment by bacongobbler** [comment]
I'm a little late to the party, but yes I agree that this is a good step forward for router-specific configuration, as well as the ability to specify global settings which will maintain backwards-compatibility. 

> However lets not add app namespace there

:+1:
