### ISSUE TITLE
generate router

### ISSUE THREAD

**Issue by stevesloka** [deis/router#129]
I'm playing around with the router in a plain vanilla k8s cluster. When I do the `helm generate router`, it says that it ran 0 generators. Is this normal? 

When I do deploy I get a permission denied error related to the service account. I'm trying to figure out if I'm not getting the template built correctly or if I've got more SELinux issues.

**Comment by bacongobbler** [comment]
@stevesloka it appears that the router chart itself does not contain any templates, so helm generate will not run any generators.

**Comment by stevesloka** [comment]
Ok sweet, sorry for the confusion, just my noobness to helm. Thanks!

**Comment by krancour** [comment]
> When I do deploy I get a permission denied error related to the service account.

Can you see if the deis-router service account exists and whether it has any secrets associated with it?

It's a known issue (which we can't do anything about) that service accounts and their secrets don't work if SSL isn't set up correctly within your k8s cluster.  i.e. the controller manager _must_ have a CA for signing API tokens, and the apiserver must trust that CA.

See #101 for more details.

**Comment by stevesloka** [comment]
Thanks @krancour, I think SSL might be my issue. My cluster in question is using tokens to auth. My other cluster which does have certs deployed just fine.
