### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by stevesloka** [deis/router#130]
I have the router up and running now. Was working through the examples. Does the router understand the nodeport or is it configured to look at the container port? 

My question is after setting up the hosts in /etc/hosts (e.g. nginx, apache, etc) and accessing via http://nginx.example.com:<nodePort> I got a 404 back from nginx. 

Where does the config get written to in the container? I wanted to validate that it actually picked up the example services. 

```
[25/Feb/2016:17:59:43 +0000] - 10.2.12.0 - - - 404 - "GET / HTTP/1.1" - 406 - "-" - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36" - "_" - - - nginx.example.com:31605 - - - 0.000
```

**Comment by krancour** [comment]
@stevesloka within the router container, the Nginx config is written to `/opt/router/conf/nginx.conf`.

**Comment by stevesloka** [comment]
I don't have /opt/router/* I only have /opt/nginx

**Comment by krancour** [comment]
> Does the router understand the nodeport or is it configured to look at the container port?

Where is your k8s cluster running?  Vagrant, AWS, other?

**Comment by stevesloka** [comment]
It's CoreOS (https://coreos.com/kubernetes/docs/latest/kubernetes-on-baremetal.html) but just running in VM's on ESXi.

**Comment by krancour** [comment]
> I don't have /opt/router/* I only have /opt/nginx

Sounds like your router image might be rather old.  Which chart did you install from?

**Comment by stevesloka** [comment]
I used "router". My image is 2.0.0-alpha. Should I build from scratch?

**Comment by bacongobbler** [comment]
@stevesloka try running `router-dev`. A lot of the concepts have changed since the alpha release, including what @krancour is trying to describe. I was helping another user with running the router on k8s last week and he found the router-dev chart to be a lot more stable.

**Comment by bacongobbler** [comment]
cc @ultimateboy to see if he has any knowledge he can share from his experience :)

**Comment by stevesloka** [comment]
Ok using the router-dev did the trick. I can route the examples correctly! Thanks for the help! Now I'm going to try and get SSL running.

**Comment by krancour** [comment]
@stevesloka I think what happened here, specifically, is that the alpha router finds routable services using the label `routable: "true"` whilst the latest image (from the `router-dev` chart) uses the label `router.deis.io/routable: "true"`.  If you were deploying the example manifests from master, the labels on those example services match the latter, but no the former (what the alpha image would have looked for).
