### ISSUE TITLE
Add automatic SSL certificate registration through letsencrypt

### ISSUE THREAD

**Issue by ultimateboy** [deis/router#134]
Currently, the SSL options provided by deis/router support manual configuration of ssl certs. There's also support for a wildcard cert. It would be ideal if deis/router provided integration with Let's Encrypt so that an ssl cert is automatically generated (and maintained overtime) for each routable service's domains.

There's an issue over in the deis/deis queue which begins to address this functionality (https://github.com/deis/deis/issues/4681) but given the functionality should probably be integrated directly into router, I'm creating an issue here in this queue, so that other people (like myself) can find it!

I don't have any immediate plans to begin implementing this functionality, but I'll keep this issue up to date when I do finally begin.

**Comment by rimusz** [comment]
+1 as I was just going to open the same issue

**Comment by krancour** [comment]
I agree that this would be a nice feature, but I wouldn't entirely agree on router being the right place to incorporate it.

There are two concerns here.  The first is a wildcard cert for the entire platform.  That is generally provided by an operator and installed at the router.  I could see incorporating this functionality there, however, letsencrypt does not currently support wildcard certs, so there is a technical barrier to implementing this.

The second concern is certs for application-specific "custom" domains.  Deis workflow is very much about _managing_ applications, whilst router is really just your web server / reverse proxy.  I would argue that managing application certs (even if in automated fashion) is a task better kept with the other management capabilities.  i.e. where it is today.

**Comment by ultimateboy** [comment]
Kent, thanks for the comments. I'm aware letsencrypt doesnt have support for registering wildcards yet, so this proposal is only for specific custom domains, not wildcard

If this functionality does not belong in router, I'd be interested in knowing where you imagine it happening today. I'm using router outside of deis today, so sadly I don't get all of the other benefits of deis' application management. Where do you see this functionality landing?

**Comment by krancour** [comment]
@ultimateboy glad to hear you're already getting some mileage out of the router.  We were really hoping for it to be very reusable beyond Deis Workflow.  I'm happy to see someone using it in that manner.

Your question is a very good one.  First, I'll defend a little better why I don't think this is the router's responsibility.  The router is a true "microservice" in that it really has a very tightly scoped purpose in life.  It plays no role whatsoever in the management of applications, domains, etc., with all of that work left to another component.  Usually that's Deis Workflow, but it could equally be an alternative PaaS or even a human operator.  It seems to me that things would become quite complicated if Workflow (or its alternatives) were responsible for app and domain management only, and were to then leave cert management to the router.  Certs _belong_ to applications.  Even if the router may use them,  they don't _belong_ to the router.

To reinforce that last statement, consider our plans to eventually make end-to-end SSL possible.  In such a case, the router is not responsible for terminating SSL, but that responsibility falls to a "sidecar" container running in the application's pod(s).  Divorcing cert management from application management would really make implementing this more challenging.

Ultimately, I guess the answer to your question is that if the functionality doesn't belong in router, it belongs wherever apps and domains are managed.  In your case, without Workflow, that may be a less than satisfying answer.  What are you using in place of Deis Workflow?  If it's some custom component, the functionality probably goes there.  If it's a human operator, then a utility or a new micro-service _just_ for facilitating cert management via letsencrypt might be the right answer.

**Comment by rimusz** [comment]
I'm cracking my brain around how to use caddyserver/nginx as a sidecar app to renew certs.
maybe to use object storage to store certs so they can be shared between deis apps

**Comment by ultimateboy** [comment]
Using caddy as a sidecar is exactly where my mind went after Kent's most recent comments. Glad to know that sounds like a good idea :)

**Comment by rimusz** [comment]
@ultimateboy check this out for lets encrypt certs renewal with nginx on k8s
https://github.com/corekube/cert-renew

**Comment by krancour** [comment]
I'm going to close this.  I think letsencrypt integration will occur eventually, but I think it's safe so say that an adequate case has been made for the router not being the component where this integration will happen.  Whether used in the context of the rest of Deis workflow or not, this functionality would be better left to whatever component actually manages the apps and their domains.

**Comment by bourquep** [comment]
@krancour Has this proposal been reopened elsewhere? I've searched for _letsencrypt_ in the repos for other Workflow components and found nothing. Having built-in letsencrypt cert generation/renewal would be great!

**Comment by bacongobbler** [comment]
Nope! This is still the only open ticket.

**Comment by bourquep** [comment]
Except that it is closed... 😜

**Comment by krancour** [comment]
@bourquep https://github.com/deis/workflow/issues/584 captures a more current line of thinking on this matter.
