### ISSUE TITLE
certs: a cert attached to a particular domain appears on another

### ISSUE THREAD

**Issue by vdice** [deis/router#136]
Consider the following case of two domains for a given app, but only attaching a cert to one:
```
$ deis domains:add domain.one
Adding domain.one to app... done
$ deis domains:add domain.two
Adding domain.two to app... done
$ deis certs:add cert-one server.crt server.key
Adding SSL endpoint... done
$ deis certs:list
    Name   | Common Name | SubjectAltName |        Expires         |   Fingerprint   | Domains |  Updated   |  Created
+----------+-------------+----------------+------------------------+-----------------+---------+------------+------------+
  cert-one | foo.com     |                | 1 Mar 2017 (in 1 year) | 25:64[...]0E:59 |         | 4 Mar 2016 | 4 Mar 2016
$ deis certs:attach cert-one domain.one
Attaching certificate cert-one to domain domain.one... done
$ deis certs:list
    Name   | Common Name | SubjectAltName |        Expires         |   Fingerprint   |  Domains   |  Updated   |  Created
+----------+-------------+----------------+------------------------+-----------------+------------+------------+------------+
  cert-one | foo.com     |                | 1 Mar 2017 (in 1 year) | 25:64[...]0E:59 | domain.one | 4 Mar 2016 | 4 Mar 2016
```
Now, when we curl both domains, we appear to see the same cert (both return 200 OK as well):
```
$ curl -kvI -sD - -H "Host: domain.one" https://app.130.211.155.186.xip.io
* Rebuilt URL to: https://app.130.211.155.186.xip.io/
*   Trying 130.211.155.186...
* Connected to app.130.211.155.186.xip.io (130.211.155.186) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: foo.com
> HEAD / HTTP/1.1
> Host: domain.one
> User-Agent: curl/7.47.1
> Accept: */*
```
```
$ curl -kvI -sD - -H "Host: domain.two" https://app.130.211.155.186.xip.io
* Rebuilt URL to: https://app.130.211.155.186.xip.io/
*   Trying 130.211.155.186...
* Connected to app.130.211.155.186.xip.io (130.211.155.186) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: foo.com
> HEAD / HTTP/1.1
> Host: domain.two
> User-Agent: curl/7.47.1
> Accept: */*
```

cc @helgi @krancour

**Comment by krancour** [comment]
I'll have to look into this further, but I suspect that what is happening is that in the absence of a server block listening for HTTPS traffic for domain.two, the traffic is flowing instead to the the server block for domain.one, because, as the only server block listening on 444, it is thus also the default server block for HTTPS.

If you were to install platform-wide SSL using a wildcard cert, this issue would go away, because it would introduce an explicit, catch-all default server block for any HTTPS traffic that didn't match any other.

In the absence of a platform-wide, wildcard SSL cert, that can't really be accomplished, since router wouldn't know what, if any cert could be used for that catch-all.

I don't see this as a bug so much as expected behavior given the circumstances, but I will check into what other recourse might exist.

**Comment by krancour** [comment]
So what I could do is _if_ a platform-wide wildcard cert has not been provided, I could use a self-signed cert for a default vhost listening on 443.  It would return just return 404s.  The downside is anyone requesting HTTPS for a domain that doesn't support it will get a cert warning that would stop them from ever getting the 404.  But this is still probably better than the behavior you have observed.

**Comment by vdice** [comment]
I see.  With the background info provided, I can proceed with writing a test using a wildcard cert to get the behavior I'm looking for.  That being said, if the 'fix' sounds reasonable, apart from simply representing an adjustment to help testing (although it is nice when those happen :)), then I'd be in support of it.

**Comment by krancour** [comment]
@vdice note that providing an SSL cert for use platform-wide must be done at the time of provisioning, so it requires an addition to the chart.  I'm not sure if your tests currently support that.

Here's the doc on how it's done:

https://github.com/deis/router#default-certificate-example
