### ISSUE TITLE
Should warn when cert-bearing secret not found

### ISSUE THREAD

**Issue by krancour** [deis/router#143]
See https://github.com/deis/router/issues/142

It would seem that router is not logging any errors (or at least warnings) in the event that a cert-bearing secret that is expected to exist is not found.

This should probably be corrected.

**Comment by bacongobbler** [comment]
It appears this has been fixed long ago: https://github.com/deis/router/blob/master/model/model.go#L373-L377

**Comment by krancour** [comment]
@bacongobbler... an error gets returned, but I don't believe it ever gets logged.
