### ISSUE TITLE
Enforce SSL on app-by-app basis

### ISSUE THREAD

**Issue by krancour** [deis/router#148]
Currently, a cluster admin (if you subscribe to the Google operational model) can enable / enforce redirects from HTTP to HTTPS _router-wide_, but it seems that it would be tremendously useful to app admins (again, if you subscribe to the Google operational model) to opt into that on an app-by-app basis _if_ their cluster admin isn't already enforcing it router-wide.

**Comment by krancour** [comment]
Relates to deis/controller#579

**Comment by sstarcher** [comment]
So currently the annotation for the router ```router.deis.io/nginx.ssl.enforce``` will force all apps through HTTPS.  Would the thought be if you wanted it to be on a case by case basis to not annotate the router with ```router.deis.io/nginx.ssl.enforce```, but to annoate the individual apps with ```router.deis.io/nginx.ssl.enforce```

**Comment by krancour** [comment]
@sstarcher that's the idea, although for people using full Workflow (not _just_ the controller) the addition of that annotation to their app's service is ideally facilitated through the `deis` CLI and the controller.
