### ISSUE TITLE
Router failing to connect to controller

### ISSUE THREAD

**Issue by kmala** [deis/router#151]
I am getting the following error pretty frequently when trying to execute any deis command
`http://deis.146.148.39.241.xip.io:30343 does not appear to be a valid Deis controller.
Make sure that the Controller URI is correct and the server is running.
Error: Get http://deis.146.148.39.241.xip.io:30343/v2/: dial tcp: lookup deis.146.148.39.241.xip.io on 75.75.75.75:53: no such host`

**Comment by helgi** [comment]
Your DNS isn't resolving `xip.io`

**Comment by krancour** [comment]
I agree this appears to be a DNS issue on the client-side, so I am closing.
