### ISSUE TITLE
Change the certificate secret to match the Ingress TLS secret format

### ISSUE THREAD

**Issue by helgi** [deis/router#154]
Supporting the [Ingress TLS secret format](http://kubernetes.io/docs/user-guide/ingress/#tls) makes us forward compatible

This is only about changing the actual keys inside the `data` portion. Router could support the current v2 format and the Ingress format at the same time with a simple `if not set` logic

/cc @aledbf @krancour 

https://github.com/deis/controller/issues/576

**Comment by krancour** [comment]
Nice find @helgi.  I would suggest that we not support both and that we just switch to this outright while we're pre-stable and still have the flexibility to make such changes.  Thoughts?

**Comment by helgi** [comment]
@krancour I'm down with that. Mostly wanted to be nice, re two formats. In case people install Beta and expect to move to RC with ease. Thoughts on migration?

**Comment by krancour** [comment]
I wouldn't worry about it.  Given the choice between tech tech on day 1 of stable or a breaking breaking change between beta and rc1, I'd take the latter.
