### ISSUE TITLE
Private Apps

### ISSUE THREAD

**Issue by rimusz** [deis/router#159]
An option to enable private Apps which are not exposed to internet

**Comment by bacongobbler** [comment]
You can do this already, but it's not exposed in the API. Just change `deis.io/routable: true` in the router service to `deis.io/routable: false`. There's nothing we need to do on the router side; just need to expose this in the API/client.

Can you please open an issue in deis/controller so we can track API enhancements there?

**Comment by rimusz** [comment]
sure, will open the same issue there 
https://github.com/deis/controller/issues/598
