### ISSUE TITLE
Document that routable services need to expose Port 80

### ISSUE THREAD

**Issue by jmccarty3** [deis/router#165]
Ran into some trouble today using the router until i figured out that the routable service needed to have 
```ports:
  - name: http
    port: 80
    targetPort: 3000
```

instead of just 
``` ports:
  - name: http
    port: 3000
```

**Comment by krancour** [comment]
I'll assume that if you're running into this, you're using the router independent of the rest of Deis Workflow... which is awesome!  We've been hoping people would indeed find this useful beyond Workflow.

I would agree that this needs to be documented.

**Comment by jmccarty3** [comment]
Yes. We are currently using this outside of the rest of the Deis stack as a replacement for our current solution / in preparation for upgrading to deis 2.0

**Comment by pixeleet** [comment]
Indeed, I was facepalming myself when I red this, yesterday I was fighting with the router as it was always giving me a 502 and was left wondering why :)
