### ISSUE TITLE
Link docs to tutorial on generating dhparams

### ISSUE THREAD

**Issue by krancour** [deis/router#183]
cc @arschles: you idea, captured here for posterity.

**Comment by bacongobbler** [comment]
is this something we need to get done for rc1 or can we do this post 2.0?

**Comment by vdice** [comment]
ping @krancour and @arschles to echo @bacongobbler's question above -- still envisioned for the `v2.0-rc1` milestone?

**Comment by krancour** [comment]
No... I believe rc2 has already been designated as a time to further address doc issues.

**Comment by krancour** [comment]
So... the router's docs actually already document the openssl command that can be used to generate this. It's workflow (the docs) that still need this documented and that's already covered by https://github.com/deis/workflow/issues/278, so I'm closing this issue, as there's nothing actionable on router here.
