### ISSUE TITLE
app_name breaks nginx conf generation

### ISSUE THREAD

**Issue by verdverm** [deis/router#185]
`kubectl logs deis-router-p4yjv --namespace deis`

```
2016/05/12 04:30:08 INFO: Starting nginx...
2016/05/12 04:30:08 INFO: nginx started.
2016/05/12 04:30:08 INFO: Router configuration has changed in k8s.
2016/05/12 04:30:08 INFO: Reloading nginx...
2016/05/12 04:30:08 INFO: nginx reloaded.
nginx: [emerg] unknown "app_name" variable
```

Where should `appConfig.Name` be set in the yaml files?

---
See commit: https://github.com/deis/router/commit/dce56d59415f5a73ecceb63cebda216f381c5512

search: https://github.com/deis/router/search?q=appConfig.Name

**Comment by krancour** [comment]
@verdverm, do you happen to be using the router without the rest if Workflow?

**Comment by verdverm** [comment]
yes, as an edge server in Kubernetes

So this only seems to be the case when there are no routable services when the router is started up.

It seems to work fine when there is already a routable service running in k8s

**Comment by bacongobbler** [comment]
That makes sense. I believe this is intentional as the router proxies requests to the service, so that has to exist. Perhaps the best way to tackle this would be to perform a check if said service exists before templating out nginx config so we can inform the user that there is no service to proxy requests to.

**Comment by krancour** [comment]
> So this only seems to be the case when there are no routable services when the router is started up.

> It seems to work fine when there is already a routable service running in k8s

I had not noticed this previously, but I'll doublecheck it. This may be a bug.
