### ISSUE TITLE
Deis router conflicts with kubernetes apiserver when running with --secure-port=443

### ISSUE THREAD

**Issue by n0n0x** [deis/router#188]
I couldn't find any info on this on previous issues, so I am opening a new one, point me in the right direction if you feel I am wrong! I am pretty new using kubernetes and deis.

**Problem:**
Right after installing deis using `helmc`, `deis-router` didn't want to join the party:

**Actual results:**
```
$ kubectl --namespace=deis get pods
NAME                          READY     STATUS              RESTARTS   AGE
[...]
deis-router-yocxy             0/1       ContainerCreating   0          7s
[...]
```

```
kubectl --namespace=deis describe pod deis-router-yocxy
Name:		deis-router-yocxy
Namespace:	deis
Node:		node1/xx.xx.xx.x
Start Time:	Mon, 16 May 2016 15:55:23 -0300
Labels:		app=deis-router
Status:		Pending
IP:
Controllers:	ReplicationController/deis-router
Containers:
  deis-router:
    Container ID:
    Image:		quay.io/deis/router:v2.0.0-beta4
    Image ID:
    Ports:		8080/TCP, 6443/TCP, 2222/TCP, 9090/TCP
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Liveness:		http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      POD_NAMESPACE:	deis (v1:metadata.namespace)
Conditions:
  Type		Status
  Ready 	False
Volumes:
  deis-router-token-dhr2v:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	deis-router-token-dhr2v
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  21s		21s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned deis-router-yocxy to node1
  20s		20s		1	{kubelet node1}				Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-yocxy_deis_bee01328-1b97-11e6-b7fa-0401e8f63f01_6e4c0567 on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use\n"

  8s	8s	1	{kubelet node1}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-yocxy_deis_bee01328-1b97-11e6-b7fa-0401e8f63f01_2d83cd85 on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use\n"
````
Error:
```
  8s	8s	1	{kubelet node1}		Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): failed to create endpoint k8s_POD.7f676988_deis-router-yocxy_deis_bee01328-1b97-11e6-b7fa-0401e8f63f01_2d83cd85 on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use\n"
````

**Expected Results:**
`deis-router` pod should start.

**Temporary Fix:**
delete the pod a few times until it is scheduled on a kubernetes node that is not running apiserver on port 443.

**Details:**
The problem is that `deis-router` was trying to start on a server that has `kube-apiserver` running and listening on port 443 already:
```
$ sudo netstat -natpv |grep LIST |grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      30858/kube-apiserve
```

**Steps to reproduce:**
1. Run `kube-apiserver` with `--secure-port=443`
2. Install deis using `helmc`
3. Have a look at `deis-router` pod running `kubectl --namespace=deis describe pod deis-router`

**Comment by krancour** [comment]
This is actually by design. Apart from the nodeports (high numbered, unprivileged ports) that the router's service will listen to on every host, router pod(s) will each _also_ bind to their host node's ports 80, 443, 2222, and 9090. The main reason for this is so on any platform where Kubernetes cannot provision an external load balancer (for example, Vagrant or bare metal), anyone wishing to manually provision a load balancer (on bare metal) or access the router directly on a given node (a likely scenario on Vagrant) will be easily able to predict what the router(s) will be listening on on each node.

This works out really well on a typical k8s cluster where the apiserver lives on a dedicated control node that doesn't also pull double duty as a worker node.  The problem you're encountering is probably unique to cases where the apiserver is running on a node that is also a worker.  Really, as far as I know, the only prevalent circumstance under which one would do that is when running _all_ of Kubernetes on a single node for development purposes.

We have tested against some such solutions, including [kube-solo](https://github.com/TheNewNormal/kube-solo-osx) and [micro-kube](https://github.com/micro-kube/micro-kube).

You've already alluded to killing the router pod until it gets rescheduled to a node that isn't hosting the apiserver, so I believe you're not in one of these single node scenarios. That being the case, the best path forward for you, if you can swing it, is to allocate a dedicated "control" node to host the apiserver.

If, for some reason, the above isn't doable, a workaround can be to remove lines like this one from the router RC's manifest in the chart _after_ fetching it, but _before_ generating and installing:

https://github.com/deis/charts/blob/master/workflow-beta4/tpl/deis-router-rc.yaml#L32

**Comment by n0n0x** [comment]
Perfect explanation. Thanks!!

**Comment by rukor** [comment]
Hi, I have the same problem, but only for port 9090. I installed kubernetes on Fedora via Ansible, and fedora has the 9090 port for its console. How can I change the port that router uses? Thanks

**Comment by bacongobbler** [comment]
@rukor some solutions were provided in [this comment](https://github.com/deis/router/issues/188#issuecomment-219567418). Are you provisioning a kubernetes master API and a worker node as the same machine? We've been testing and installing the router on a minimum 2-node cluster where one is the master and one is the worker node.

**Comment by rukor** [comment]
Hi, I provision kubernetes on 1 master and 3 nodes. But the nodes do have a default fedora installation so port 9090 is being used.

**Comment by krancour** [comment]
@rukor find the section in your chart that looks like [this](https://github.com/deis/charts/blob/e27895cf33b7198b857183d7ab162b7997c3b52e/workflow-dev/tpl/deis-router-deployment.yaml#L50-L58) and remove it before install.

**Comment by rukor** [comment]
@krancour Hi, thanks for this. I initially tried changing the port to 9091 then including the health and liveness ports, but it still didnt start as it was complaining of liveness issues. Do I need to remove those bits as well? Thanks

**Comment by krancour** [comment]
Removing what I linked to removes mappings from container ports to specific, well-known host ports. Tgat should have no bearing on readiness or liveness probes.

**Comment by rukor** [comment]
@krancour Thanks a lot

**Comment by rukor** [comment]
Hi @krancour I did what you suggested and still have the same problem:

```sh 
$ kubectl --namespace=deis describe pod deis-router
Name:           deis-router-2114212604-8a5eq
Namespace:      deis
Node:           192.168.1.25/192.168.1.25
Start Time:     Fri, 02 Sep 2016 14:05:26 +0100
Labels:         app=deis-router,pod-template-hash=2114212604
Status:         Pending
IP:
Controllers:    ReplicaSet/deis-router-2114212604
Containers:
  deis-router:
    Container ID:
    Image:              quay.io/deis/router:v2.4.0
    Image ID:
    Ports:              8080/TCP, 6443/TCP, 2222/TCP
    QoS Tier:
      cpu:              BestEffort
      memory:           BestEffort
    State:              Waiting
      Reason:           ContainerCreating
    Ready:              False
    Restart Count:      0
    Liveness:           http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Readiness:          http-get http://:9090/healthz delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment Variables:
      POD_NAMESPACE:    deis (v1:metadata.namespace)
Conditions:
  Type          Status
  Ready         False 
Volumes:
  deis-router-token-swrpc:
    Type:       Secret (a volume populated by a Secret)
    SecretName: deis-router-token-swrpc
Events:
  FirstSeen     LastSeen        Count   From                    SubobjectPath   Type            Reason          Message
  ---------     --------        -----   ----                    -------------   --------        ------          -------
  59m           59m             1       {kubelet 192.168.1.25}                  Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container bb3a5d6b58e28230bed08b7014a78375d78401a668404a1d82ea28aa22e86c13: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  57m   57m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 1278bcf3c0f575020215672adec30d638299a112dec9636c21efbcfec108bf35: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  55m   55m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container b45d2f78bbb00737870edb5e2b70b43234638227ff17491fd140d3f9acb43548: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  53m   53m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container e7b7df8a5a03cc2798a4d1afc3a27eb0571b7c21f1f9714bd1e652c228333819: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  52m   52m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 8c6306436a23d844b8ef76442a33d41e422187073cbc957d415c78dabb52b815: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  49m   49m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container 700a5cc671beed5d005dad0881274a7b6747316de3012c17b31939d395eaae65: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  48m   48m     1       {kubelet 192.168.1.25}          Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "POD" with RunContainerError: "runContainer: API error (500): Cannot start container a585700c936aa2740ff5537725852519827a56deaa27653ff9995a60eeb8d217: [9] System error: Failed to activate service 'org.freedesktop.systemd1': timed out\n"

  46m   14s     27      {kubelet 192.168.1.25}          Warning FailedSync      (events with common reason combined)
```

And get pods gives:

```sh
$ kubectl --namespace=deis get pods
NAME                                     READY     STATUS              RESTARTS   AGE
deis-builder-1565561396-csdq9            0/1       ContainerCreating   0          1h
deis-controller-718090620-rmoxy          0/1       CrashLoopBackOff    18         1h
deis-database-awbhh                      1/1       Running             9          1h
deis-logger-fluentd-exk3n                0/1       ContainerCreating   0          1h
deis-logger-fluentd-i57uh                1/1       Running             0          1h
deis-logger-fluentd-o4jf1                1/1       Running             0          1h
deis-logger-kdhyt                        1/1       Running             5          1h
deis-logger-redis-djlpr                  1/1       Running             0          1h
deis-minio-3454i                         0/1       ContainerCreating   0          1h
deis-monitor-grafana-iwj6r               1/1       Running             0          1h
deis-monitor-influxdb-bynyg              0/1       ContainerCreating   0          1h
deis-monitor-telegraf-il56e              0/1       ContainerCreating   0          1h
deis-monitor-telegraf-qoz6t              1/1       Running             0          1h
deis-monitor-telegraf-vwkaj              1/1       Running             1          1h
deis-nsqd-5119r                          1/1       Running             0          1h
deis-registry-1365764545-b7aoe           0/1       CrashLoopBackOff    21         1h
deis-registry-proxy-ejgll                0/1       ContainerCreating   0          1h
deis-registry-proxy-jrbru                1/1       Running             0          1h
deis-registry-proxy-zp4po                1/1       Running             0          1h
deis-router-2114212604-8a5eq             0/1       ContainerCreating   0          1h
deis-workflow-manager-3997897580-ztj73   1/1       Running             0          1h
```

**Comment by krancour** [comment]
@rukor the error you're experiencing is _not_ the same error that was described by this thread's OP. 

The error you're experiencing is:

```
Failed to activate service 'org.freedesktop.systemd1': timed out\n
```

I'm not sure what that means, precisely. (Initial guess is this might be Fedora specific.)  You would be better off opening a new issue for this.

**Comment by stcqu** [comment]
I ran into this issue as well.  Is there a reason not to expose these ports by changing the the service type from LoadBalancer to NodePort instead of a pod HostPort?

**Comment by krancour** [comment]
@stcqu the reason was so that when you run router locally on something like minikube, you can reliably expect traffic sent on ports 80 and 443 on that VM to reach the router. In retrospect, it probably didn't _have_ to be that way, but when we are first starting to re-platform on k8s, that capability seemed desirable, as we had it previously. I do still think it's a nice convenience for anyone taking their first test drive. If it doesn't suit you, fork the chart. We have always intended for people to make customizations as they see fit.

**Comment by stcqu** [comment]
@krancour Thanks.  Makes sense.  I forked it and I'll push a commit with those changes sometime soon for other people that might want to schedule on the master node or have a similar use case.
