### ISSUE TITLE
deis-router: x509: certificate signed by unknown authority.

### ISSUE THREAD

**Issue by rimusz** [deis/router#200]
on RC2 got the error on Kube Solo/Cluster Apps: `Error building model; not modifying certs or configuration: Get https://10.100.0.1:443/api/v1/namespaces/deis/replicationcontrollers/deis-router: x509: certificate signed by unknown authority.`

Any way to bypass it?

**Comment by sstarcher** [comment]
I get the same error with RC2.  Reverting back to RC1 allows my platform cert to work correctly.

When using Deis RC2 I'm seeing a cert from deis getting returned and not my platform cert.

**Comment by krancour** [comment]
@rimusz can you share the steps I can use to reproduce this?

**Comment by rimusz** [comment]
nothing too special, usual workflow install on kube-solo app, have not tested on GKE yet, as I'm at CoreOS London meetup

**Comment by krancour** [comment]
@rimusz you've added a platform cert?

**Comment by krancour** [comment]
@rimusz @sstarcher I will check further, but I believe you might both have run into this:

https://github.com/deis/router/pull/194

**Comment by sstarcher** [comment]
@krancour ooooh the format was changed to `tls.crt`... ya let me try that

**Comment by rimusz** [comment]
nope,I have not

**Comment by krancour** [comment]
@rimusz I'm not sure how this problem could occur for anyone not using TLS at all.

**Comment by sstarcher** [comment]
@krancour I confirmed, that was my issue.

**Comment by krancour** [comment]
Great @sstarcher.  Thanks!

Waiting to hear more from @rimusz on this before closing.

**Comment by rimusz** [comment]
it looks like my kube apps need tls support, will look to that more deeply tomorrow

**Comment by rimusz** [comment]
@krancour I'm closing this one, as I cannot reproduce it on the fresh kube-solo and workflow install anymore.
The problem was caused when RC1 was fully deleted and I tried to install RC2.
