### ISSUE TITLE
Add http2 listen support.

### ISSUE THREAD

**Issue by tmc** [deis/router#204]

**Comment by abourget** [comment]
There is no http2 support right now ?

**Comment by felixbuenemann** [comment]
@tmc You should probably have added a description.

I've looked at the generated nginx.conf and nginx version.

The router currently uses nginx 1.10.1, so enabling http2 support should be as easy as adding `http2` to the `listen 6443` directive in the nginx.conf.

**Comment by felixbuenemann** [comment]
I've pushed PR #216 which enables http2.
