### ISSUE TITLE
Routing only work with Type: LoadBalancer not with Type: NodePort

### ISSUE THREAD

**Issue by pixeleet** [deis/router#223]
I'm using the `router` standalone without workflow on AWS.

I've managed to set up everything properly, SSL certificates work out of the box, happy happy joy joy!

But. If I provision the ELB with `Type`, `LoadBalancer` setting in the `Service`, it only gets attached to one of the two AZs, therefore I have to touch the config by hand to update it to have all AZs, and then add it to R53, so I've decided to put it into terraform.

However, if I declare an ELB with the exact same settings as the Service would provision if I use `Type`, `LoadBalancer`, while using `Type: NodePort` the router will not resolve. 

What would be the cause to this? To my understanding configuring an ELB by hand (or terraform) to do the same thing should work, but then it doesn't. What am I missing here?

**Comment by kmala** [comment]
How did you provision the cluster using the federation api (http://kubernetes.io/docs/user-guide/federation/federated-services/) or a basic multi zone one(http://kubernetes.io/docs/admin/multiple-zones/)?
If it is basic multizone load balancer will show as attached to single zone  where the master is running but will route  to all the pods present in different zones.

**Comment by pixeleet** [comment]
@kmala I went with the _basic_ setup, so I'm not using Federated Services yet.
To expand a bit more on the issue:

The goal here is that I'd like to provision the ELB with terraform, rather then have the `Service` create an ELB for me, keeping state and control of the ELBs in terraform is necessary to achieve a beautiful well managed infrastructure. 

To my understanding using `NodePort` would open the port and forward to kube-proxy on all nodes. However when I set up an ELB with the exact same settings that `deis-router`'s `Service` would provision it doesn't resolve ever. What would be the cause to that?

**Comment by kmala** [comment]
Yes, when you use NodePort k8s will open port and all your request on that port and ip of your nodes will route to the service.If you have your own ELB then route the traffic from ELB to the <node_ip>:<Node port of the service> .
What is the exact issue which you are facing?

**Comment by pixeleet** [comment]
Given two ELBs, one created by the `deis-router` kubernetes `Service` and one created by my humble self. Both have been configured to listen and proxy to the same ports. Yet, only the one created by the `Service` will actually resolve.

Meaning that whenever I set the `Service` created ELB in R53 as CNAME for my domain it will resolve at that domain, while if I use the ELB I've created the domains will not resolve. 

The output below is from `aws elb describe-load-balancers --output json` command.

So here's one ELB created by the `Service` 
```
{
            "Subnets": [
                "subnet-9d17d3f5"
            ],
            "CanonicalHostedZoneNameID": "Z215JYRZR1TBD5",
            "CanonicalHostedZoneName": "abe298ec45d3b11e6befb02ddcbcdf6b-204943019.eu-central-1.elb.amazonaws.com",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 32418,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 9090,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 31433,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 443,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 32222,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 2222,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 31080,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 80,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                }
            ],
            "HealthCheck": {
                "HealthyThreshold": 2,
                "Interval": 10,
                "Target": "TCP:31080",
                "Timeout": 5,
                "UnhealthyThreshold": 6
            },
            "VPCId": "vpc-3e1d1257",
            "BackendServerDescriptions": [],
            "Instances": [
                {
                    "InstanceId": "i-03decbe7064d6bde1"
                },
                {
                    "InstanceId": "i-04d9d0dce91037b02"
                },
                {
                    "InstanceId": "i-0b834e948d6cb4afa"
                },
                {
                    "InstanceId": "i-05730020f2adb37c1"
                },
                {
                    "InstanceId": "i-0f7e4b2aa841d6a60"
                }
            ],
            "DNSName": "abe298ec45d3b11e6befb02ddcbcdf6b-204943019.eu-central-1.elb.amazonaws.com",
            "SecurityGroups": [
                "sg-7b5ddc13"
            ],
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "ELBSecurityPolicy-2015-05"
                ]
            },
            "LoadBalancerName": "abe298ec45d3b11e6befb02ddcbcdf6b",
            "CreatedTime": "2016-08-08T07:43:07.150Z",
            "AvailabilityZones": [
                "eu-central-1a"
            ],
            "Scheme": "internet-facing",
            "SourceSecurityGroup": {
                "OwnerAlias": "250831504436",
                "GroupName": "k8s-elb-abe298ec45d3b11e6befb02ddcbcdf6b"
            }
        }
```

And then here's one created by me.
```
{
            "Subnets": [
                "subnet-2167765a",
                "subnet-ba599fd2"
            ],
            "CanonicalHostedZoneNameID": "Z215JYRZR1TBD5",
            "CanonicalHostedZoneName": "web-bannerwise-io-1992915525.eu-central-1.elb.amazonaws.com",
            "ListenerDescriptions": [
                {
                    "Listener": {
                        "InstancePort": 32418,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 9090,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 31080,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 80,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 32222,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 2222,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                },
                {
                    "Listener": {
                        "InstancePort": 31443,
                        "SSLCertificateId": "arn:aws:iam::250831504436:server-certificate/star_bannerwise_io",
                        "LoadBalancerPort": 443,
                        "Protocol": "SSL",
                        "InstanceProtocol": "SSL"
                    },
                    "PolicyNames": [
                        "ELBSecurityPolicy-2015-05"
                    ]
                }
            ],
            "HealthCheck": {
                "HealthyThreshold": 2,
                "Interval": 30,
                "Target": "TCP:31080",
                "Timeout": 3,
                "UnhealthyThreshold": 10
            },
            "VPCId": "vpc-3e1d1257",
            "BackendServerDescriptions": [],
            "Instances": [
                {
                    "InstanceId": "i-03decbe7064d6bde1"
                },
                {
                    "InstanceId": "i-04d9d0dce91037b02"
                },
                {
                    "InstanceId": "i-05730020f2adb37c1"
                },
                {
                    "InstanceId": "i-0b834e948d6cb4afa"
                },
                {
                    "InstanceId": "i-0f7e4b2aa841d6a60"
                }
            ],
            "DNSName": "web-bannerwise-io-1992915525.eu-central-1.elb.amazonaws.com",
            "SecurityGroups": [
                "sg-245adb4c"
            ],
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "ELBSecurityPolicy-2015-05"
                ]
            },
            "LoadBalancerName": "web-bannerwise-io",
            "CreatedTime": "2016-08-08T07:38:40.240Z",
            "AvailabilityZones": [
                "eu-central-1a",
                "eu-central-1b"
            ],
            "Scheme": "internet-facing",
            "SourceSecurityGroup": {
                "OwnerAlias": "250831504436",
                "GroupName": "web-bannerwise-io"
            }
        },
```

**Comment by krancour** [comment]
Ok. There's a whole bunch going on in the back and forth in this thread. So I'm going to just give you a quick rundown on a few simple things you can check into.

1. You've mentioned issues with one of your load balancers "not resolving." Do you literally mean that `dig` or `nslookup` are not showing you the IP(s) you expect when you query the domain name you believe you have configured as a CNAME for one of your ELBs? If so, you have a DNS issue and it's not really k8s or workflow related at all.

2. I'm guessing the above is _not_ the case-- that there is no DNS issue, and you simply cannot successfully access your app via the ELB you created yourself with Terraform. The most likely reason for this has to do with security groups. When k8s provisions an ELB for a service of `Type: LoadBalancer`, it will create a security group for that ELB _and_ the security group used for the worker nodes will be modified to permit ingress from the ELB's security group. Chances are high that your worker nodes are not permitting ingress from your Terraform-created ELB.

3. This advice is somewhat orthogonal to your inquiry, but may still help you... Router has pre-accounted for these sort of scenarios where someone is _not_ (or _can not_) use an ELB or other cloud-based load balancer (for example, on Vagrant or bare metal). This can be helpful in your case as well where you intend to use an ELB you provisioned yourself. You do _not_ need to set the service's type to _either_ `NodePort` _or_ `LoadBalancer`. (i.e. remove that line from the chart altogether if you wish). What happens already is that the router pods _do_ bind to _host_ ports 80, 443, 2222, and 9090. You can set up your Terraform-provisioned ELB to work with those ports. (But remember, you will still need to make sure the security group on the worker nodes permits ingress from your ELB.

Hopefully this helps a bit. If not, please let me know.

**Comment by pixeleet** [comment]
hey @krancour 

1. No, the DNS Query does resolve, however, when I'm trying to resolve the service at `testing.domain.tld` that just won't work. 

2. That's a viable situation, I'll make sure the SG I'm creating for the ELB is permitted to access the worker nodes.

3. So generally speaking, 80, 443, 2222, and 9090 will act as if they were NodePorts?

Let me quickly look into 2. and get back to you! 

Thanks for the detailed answer!

Cheers,
David

**Comment by krancour** [comment]
@pixeleet see edit I made above as well... adding a health check is also going to help you.

**Comment by pixeleet** [comment]
@krancour I've tried fixing option 2, but apparently even if the ELB is in an SG that is allowed to access literally everything in the worker's SG, still not getting the expected behaviour. 

Did you try setting up an ELB by hand before for the router? 
is there some internal magic going on in deciding if traffic can go through or not?

**Comment by krancour** [comment]
I've done it by hand before. There's no internal magic either.

Can you confirm you have followed these steps?

1. Created new ELB having some security group, e.g. `MyK8sELB`
1. Map listeners on ELB as follows:
    * Listener: TCP/80; Backend: TCP/80
    * Listener: TCP/443; Backend: TCP/443
    * Listener: TCP/2222; Backend: TCP/2222
    * Listener: TCP/9090; Backend: TCP/9090
1. Add healthcheck:
    * Port: 9090; Protocol: HTTP; Endpoint: /healthz
1. Ensure k8s workers' security group permits ingress on all ports mentioned above from the ELB's security group.
1. Have _all_ the k8s workers added to the backend pool.

If setup exactly as described, then take a look and see whether the ELB is regarding any of the worker nodes as healthy and in service. The _only_ nodes considered healthy should be _only_ the ones currently hosting a router pod. They would be the only ones to receive traffic. If router pod(s) should happen to shift around the cluster over time, the nodes that the ELB regards as healthy will change.

**Comment by pixeleet** [comment]
Hey @krancour 

1. Create an ELB with some security group, which in turn is enabled to access worker SG.
![screen shot 2016-08-09 at 17 04 40](https://cloud.githubusercontent.com/assets/5776997/17521388/71d3e716-5e53-11e6-8ea1-7c9bc9a69e4b.png)

2. Map listeners.
![screen shot 2016-08-09 at 17 08 55](https://cloud.githubusercontent.com/assets/5776997/17521524/fd4fcd82-5e53-11e6-8f85-626628927be6.png)
While I do understand that it's strange that we map SSL to SSL but then this is exactly what I see the ELB created by the router doing. 

3. Added healthcheck but apparently it fails on 9090/healthz while it succeeds on 80/healthz?
===> 9090/healthz
![screen shot 2016-08-09 at 17 07 58](https://cloud.githubusercontent.com/assets/5776997/17521504/e7e86d3c-5e53-11e6-9006-d555a8483368.png)
![screen shot 2016-08-09 at 17 07 42](https://cloud.githubusercontent.com/assets/5776997/17521505/e7e95062-5e53-11e6-9c29-32c6a12b3db2.png)
===> 80/healthz
![screen shot 2016-08-09 at 17 10 38](https://cloud.githubusercontent.com/assets/5776997/17521627/491f6038-5e54-11e6-8211-98f311746f1b.png)
![screen shot 2016-08-09 at 17 10 50](https://cloud.githubusercontent.com/assets/5776997/17521632/4d447edc-5e54-11e6-84f4-9789d315b716.png)

4. Make sure ELB SG can access worker SG.
![screen shot 2016-08-09 at 17 09 50](https://cloud.githubusercontent.com/assets/5776997/17521586/222613dc-5e54-11e6-8eef-7dd5d8a8c9fa.png)

5. All the nodes are part of the ELB.
![screen shot 2016-08-09 at 17 14 17](https://cloud.githubusercontent.com/assets/5776997/17521747/bddf3ccc-5e54-11e6-99b8-e4edd1a9b38b.png)

Is there something strange in this flow?

**Comment by krancour** [comment]
@pixeleet a few things...

I have not ever actually seen services of `Type: LoadBalancer` create ELBs with SSL -> SSL mappings like you have. I'm not doubting you have seen that. I'm just saying it appears unusual to me. Have you tried with TCP just to see what happens?

The healthcheck endpoint `/healthz` _is_ exposed on both 80 and 9090. The reason it's exposed on two is because, depending on how your router(s) are configured, port 80 _might_ be using PROXY protocol and ELBs don't set the headers required by PROXY protocol when performing a healthcheck. On port 9090, the router exposes the healthcheck with a guarantee that PROXY protocol isn't in play. This makes it a more reliable choice for this case. It's quite odd to me to see that healthcheck passing on port 80, but _not_ on 9090. This _might_ point to the problem...

When you do the heathcheck on port 80 and the ELB reports two nodes in service, are you actually able to reach your application(s)? What I am suspicious of is that `/healthz` is a frequently used endpoint for healthchecks in the k8s world. I am wondering about the possibility that is it not the router, but rather something else that is answering positively when you do the healthchecks on port 80. I see two nodes listed as "InService." Have you actually scaled the router to two instances? If not, this is a dead giveaway that something else is receiving that traffic.

**Comment by pixeleet** [comment]
Indeed it's strange that 80 works but 9090 doesn't. Yes I have two router
nodes so that's correct at least.

**Comment by krancour** [comment]
@pixeleet and you can get traffic through to your applications with that configuration?

**Comment by pixeleet** [comment]
I did verify that I can but ill check again once I'm home, ~30mins

**Comment by krancour** [comment]
@pixeleet if things do indeed work with that configuration, what I'd be very interested in is if you can ssh to a worker node (one that is `InService`) and maybe try curling `localhost:9090/healthz` to see what's happening.

**Comment by pixeleet** [comment]
@krancour Sorry, bit late

So I've logged in to a worker node, and did curl `localhost:9090/healthz`.
As `docker ps` shows, it is running.

Ideas?

```
core@ip-10-0-10-189 ~ $ curl localhost:9090/healthz
curl: (7) Failed to connect to localhost port 9090: Connection refused
core@ip-10-0-10-189 ~ $ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                 NAMES
3d2f4312b0a7        quay.io/deisci/router:git-4024db4                     "/opt/router/sbin/boo"   10 hours ago        Up 10 hours                                                                               k8s_deis-router.c8f63f07_deis-router-10rbw_deis_348b3e23-5e08-11e6-888a-029a2378472b_a3a0b118
```

**Comment by pixeleet** [comment]
I'm going to go and try isolating the issue. 

So far I've managed to verify, that if I use the SG I've created with terraform on the ELB created by deis/kube I'm still able to access my instances, so the SG configuration is ok. 

Moving forward on checking Node configuration and will get back to you if I see something funky.

**Comment by pixeleet** [comment]
Okay, I must admit, I do feel stupid. In fact, everything in the setup was correct, except for one small detail that managed to escape my attention, apparently, the ELB was attached to both AZs, respectively eu-central-1a and eu-central-1b but to the private ones.

I'm closing the issue, thanks for your help @krancour.

**Comment by krancour** [comment]
@pixeleet ahh... I have made that mistake before as well.
