### ISSUE TITLE
Validation of router.deis.io/nginx.ssl.ciphers too strict

### ISSUE THREAD

**Issue by felixbuenemann** [deis/router#227]
The `router.deis.io/nginx.ssl.ciphers` annotation on the rc currently does not allow excluding groups of ciphers using exclamation marks or using combinations with pluspr, like the one recommended by the mozilla foundation or cloudflare:

Example:
```
EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5
```

The problem is [this regex in model.go](https://github.com/deis/router/blob/11e2f420cc2f8f46f1951d7ca76d23e92200eee8/model/model.go#L154):

```go
Ciphers           string      `key:"ciphers" constraint:"^([A-Z][A-Z\\d-]+:?)*$"`
```

This should be changed to something like:

```go
Ciphers           string      `key:"ciphers" constraint:"^(!?[A-Z][A-Z\\d+-]+:?)*$"`
```

Note the addition of the leading optional `!` and the `+` charachter in the second character group.

**Comment by krancour** [comment]
This is easy enough to fix. Note that the `+` should be escaped because of its special meaning.

**Comment by felixbuenemann** [comment]
@krancour No, you don't need to escape the `+` inside a character group (it doesn't hurt either, it's just redundant).

Thanks, for implementing!

**Comment by krancour** [comment]
> you don't need to escape the + inside a character group

I wasn't aware of that. Good info. Thanks @felixbuenemann!
