### ISSUE TITLE
attaching `router.deis.io/routable: "false"` still makes the app routable

### ISSUE THREAD

**Issue by bacongobbler** [deis/router#233]
Given the following service and pod:

```
><> k --namespace=go get svc go -o yaml | grep routable
    router.deis.io/routable: "false"
><> k --namespace=go get po
NAME                      READY     STATUS    RESTARTS   AGE
go-web-1352584931-xvvl9   1/1       Running   0          3m
```

If I attempt to hit the router for that app, it still accepts traffic:

```
><> cat /etc/hosts | grep go
10.245.1.3	k8s.local deis.k8s.local deis-builder.k8s.local deis-workflow-manager.k8s.local deis-minio.k8s.local go.k8s.local foo.k8s.local bar.k8s.local car.k8s.local star.k8s.local www.k8s.local
><> curl go.k8s.local
Powered by Deis
Release v5 on go-web-1352584931-xvvl9
```

Is there a value I can pass to the annotation to disable routing, or do I have to completely remove the annotation from the service to drop requests?

**Comment by bacongobbler** [comment]
Hmm, even if I completely remove the annotation it seems like the router doesn't pick up on this.

**Comment by helgi** [comment]
Are you looking at the labels or annotations? in your controller code you are using labels

**Comment by bacongobbler** [comment]
Labels, sorry.

**Comment by krancour** [comment]
Wow... really, wow...

I can confirm this bug. I'm looking into it.

**Comment by krancour** [comment]
Oh wait... @bacongobbler already did.
