### ISSUE TITLE
Any doc to help manual setup Front-facing load balancer ?

### ISSUE THREAD

**Issue by wenerme** [deis/router#241]
I install k8s on bare metal using docker-multinode, how can I make deis work on my k8s ?

**Comment by krancour** [comment]
https://github.com/deis/router/blob/master/README.md#manually-configuring-a-load-balancer

**Comment by wenerme** [comment]
I am new to kubernetes, just want to get a running deis(not Vagrant),

```
user agent (browser) --> front-facing load balancer --> kube-proxy on _any_ Kubernetes worker node --> _any_ Deis router pod --> kube-proxy on that same node --> _any_ application pod
```

I know what I need but how?

**Comment by krancour** [comment]
@wenerme are you all set now?

The documentation I linked you to enumerates the options that are available.

Perhaps what isn't clear is where the load balancer itself comes from? I guess what's not explicitly states is that in this sort of scenario, you need to manually provision and configurea load balancer or proxy of some sort _outside_ your cluster. You could use Nginx or HAProxy for that purpose.
