### ISSUE TITLE
Custom Domains and HTTPS Enforcing

### ISSUE THREAD

**Issue by pixeleet** [deis/router#247]
Hey Guys, I have a problem with SSL not being enforced on a custom domain only on the `platformDomain`, is there a way to makes sure that HTTPS is enforced on custom domains too?

**Comment by krancour** [comment]
@pixeleet did you provide a cert for the custom domain in question and attach it to that domain?

**Comment by pixeleet** [comment]
A cert is attached with `deis certs:attach star-custom-domain sub.custom.domain`

**Comment by pixeleet** [comment]
```
star-custom-domain | *.custom.domain   | *.custom.domain,custom.domain           | 4 Jul 2017 (in 1 year)    | BC:27[...]D9:60 | sub.custom.domain,another.custom.domain
```

**Comment by pixeleet** [comment]
I did replace the client's domain to `custom.domain` through the examples but this is the output I have from `deis certs` pasted above.
