### ISSUE TITLE
add a model_test.go

### ISSUE THREAD

**Issue by arschles** [deis/router#25]
#23 introduces non-trivial functionality, so we should have tests for it

**Comment by krancour** [comment]
Just wanted to quickly comment that I had not lost track of this.  I desperately want to add these tests as well, but figuring out how to test things that have dependencies on the k8s API has been elusive.  I think this is going to be the subject of some discussion as a team next week.

**Comment by krancour** [comment]
#104 introduced _some_ tests against the model.  They revolve mainly around validation.  The model uses a very declarative style, so these tests don't do much to increase coverage.  (And interesting example of how coverage numbers can lie to you.)

The original issue here though does revolve more around actual imperative logic that is not covered by unit tests, but unless I am mistaken, we're resigned at this point to the notion that code that interacts with k8s will be covered by e2e tests instead.

My feeling is that this should be closed in light of the above, but can be re-opened someday if the possibility of testing the model in isolation from k8s becomes a more realistic possibility.
