### ISSUE TITLE
vendor/ directory still owned by root in CI

### ISSUE THREAD

**Issue by mboersma** [deis/router#258]
I noticed yesterday that a `router-pr` job was stuck on Jenkins. A shell into the node showed that the `workplace/router-pr/vendor/` directory was owned by root, a problem we'd seen before. Deleting the directory let the job continue to run, but it immediately recreated the owned-by-root problem.

**Comment by vdice** [comment]
See also https://github.com/deis/jenkins-jobs/issues/209

**Comment by bacongobbler** [comment]
semi-resolved via https://github.com/deis/ci-manager/pull/8
