### ISSUE TITLE
Proposal: use ConfigMap instead of annotations (when available)

### ISSUE THREAD

**Issue by aledbf** [deis/router#26]
[ConfigMap](https://github.com/kubernetes/kubernetes/pull/6245) (scheduled for 1.2)

**Comment by krancour** [comment]
@aledbf can you clarify the meaning of "when available?"

Are you proposing that we use this feature outright when 1.2 is releases (thereby losing 1.1 compatibility)?

Or are you proposing that we detect the availability of the feature and use it if it's there?

**Comment by krancour** [comment]
Direction seems to be that we need to maintain compatibility with k8s 1.1.  That pretty much eliminates any possibility of this.  This is something that could be reconsidered in the v3 timeframe, but since that's way off on the distant horizon, I'm closing this for now.
