### ISSUE TITLE
support GCP Internal LB

### ISSUE THREAD

**Issue by rimusz** [deis/router#283]
Support for GCP [Internal LB](https://cloud.google.com/compute/docs/load-balancing/internal/) would be nice to have in router via annotations as there is for AWS internal ELB:
`service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`

**Comment by bacongobbler** [comment]
This should already work out of the box. Since the internal load balancer needs to be created manually through the console, just point it to the router as described in the frontend configuration. Change the port number to 8080 and it should be hitting the router.

**Comment by krancour** [comment]
@rimusz I think this is a k8s feature request. Router (router's chart, really) can't offer that as an option until / unless k8s GCP cloud provider has support for specifying that a `service` of `type: Loadbalancer` is internal (via annotations, as is currently supported by the AWS cloud provider for ELBs).

I'm going to close this, but you can re-open it if/when k8s has support for this. (If they do already and I am overlooking it, point us in the right direction.)
