### ISSUE TITLE
HPKP Public-Key-Pins Header

### ISSUE THREAD

**Issue by deis-admin** [deis/router#306]
_From @wenzowski on June 18, 2015 19:48_

If an etcd flag were to enable nginx to serve HPKP headers...
1. Should Deis automatically extract the `pin-sha256` for each public key configured in etcd?
2. Should Deis expose a unified `report-uri` to collect pinning failure reports from User-Agents?

HPKP is covered by [RFC 7469](https://tools.ietf.org/html/rfc7469) and there's a summary [on MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning)

_Copied from original issue: deis/deis#3899_

**Comment by deis-admin** [comment]
_From @croemmich on June 18, 2015 20:21_

> Should Deis automatically extract the pin-sha256 for each public key configured in etcd?

That would be my preference. You could maybe allow it to be manually set per domain with etcd keys, but that adds another level of complexity.

> Should Deis expose a unified report-uri to collect pinning failure reports from User-Agents?

I don't think Deis should implement the endpoint to collect failures, but maybe allow a url to be set in an etcd key? That way people can implement it if they chose to.

**Comment by deis-admin** [comment]
_From @technosophos on June 19, 2015 16:51_

Regarding question 2, how vital is a functioning `report-uri` to the overall success of HPKP?

**Comment by deis-admin** [comment]
_From @wenzowski on June 19, 2015 18:16_

If the ops team doesn't have a monitored endpoint to collect client failures, HPKP becomes a black box that prevents an unknown portion of connection attempts.

**Comment by deis-admin** [comment]
_From @wenzowski on June 19, 2015 18:21_

...validation failures are documented in [section 3](https://tools.ietf.org/html/rfc7469#section-3)

**Comment by krancour** [comment]
Workflow's (v2's) router no longer proxies etcd like v1 did, as no Workflow component has a direct dependency on etcd. Closing this as inapplicable to our current state.
