### ISSUE TITLE
GKE Failed: Create Address error`

### ISSUE THREAD

**Issue by Blystad** [deis/router#342]
Hey, I'm running on Google Container Engine. Initially on 1.5.6, but then I upgraded to 1.6.1 (which I afterwards learned that it would break all `git push`, but...gave me an excuse to setup docker build for all images, so something positive came out of it).

Latest version of Workflow.

First issue I saw was that suddenly some of my requests would hang forever. I manually added a healthcheck to the load balancer, and that worked around the issue:

![image](https://cloud.githubusercontent.com/assets/324506/25491223/94bfb612-2b6f-11e7-8353-39431c84941f.png)

Then I decided now to check the cloud console, and I saw a lot of errors related to Deis Router:

![image](https://cloud.githubusercontent.com/assets/324506/25491129/550e9f24-2b6f-11e7-9a2b-596362f78147.png)

Any suggestions on how to fix this would be appreciated. I'm currently migrating everything from Deis 1.13 on AWS to Deis Workflow on GKE.

**Comment by krancour** [comment]
This looks like an internal GCP error having nothing to do with the router other than a coincidence that the IP it's unable to reserve happens to be _for_ the router.

**Comment by Blystad** [comment]
I "Fixed" it by reconfiguring deis-router as `type: ClusterIP`, and then as `type: LoadBalancer` (Which created a new load balancer).

Could be related to my experimentation. I'll close this issue, and hope that the issue doesn't surface again.
