### ISSUE TITLE
Pod goes into `CrashLoopBackoff` repeatedly

### ISSUE THREAD

**Issue by mboersma** [deis/router#44]
Installing deis-router through the deis helm chart leaves me with deis-router continually flapping:
```console
$ kubectl get pods
NAME                        READY     STATUS              RESTARTS   AGE
deis-builder-lknfs          0/1       CrashLoopBackOff    16         1h
deis-database-yxntz         1/1       Running             0          1h
deis-etcd-1-ekw9s           1/1       Running             0          1h
deis-etcd-1-hrqyk           1/1       Running             0          1h
deis-etcd-1-pd1mu           1/1       Running             1          1h
deis-etcd-discovery-vqlzu   1/1       Running             0          1h
deis-minio-fsmqx            0/1       RunContainerError   0          1h
deis-registry-rarvy         1/1       Running             0          1h
deis-router-2iwxb           0/1       CrashLoopBackOff    15         1h
deis-workflow-tr7eb         1/1       Running             1          1h
```

**Comment by arschles** [comment]
noticed this too, but it's intermittent between `helm install`s. Possibly etcd related? Although I haven't seen any consistent etcd behaviors that could cause

**Comment by mboersma** [comment]
So far deis-router has consistently failed for me, and etcd is happy and healthy. There's no `Service` defined for deis-router, and the `ReplicationController` doesn't show any valuable info, but if anyone knows where I could get relevant failure logs, I'll post them here.

**Comment by krancour** [comment]
@mboersma I'll look into this.  fwiw, router doesn't use etcd at all, so the problem definitely isn't there.

**Comment by krancour** [comment]
The problem is here:

https://github.com/deis/router/blob/master/model/model.go#L227-L236

This is me trying to determine whether a service actually has any pods backing it ATM.  If not, router returns a 503 when requests for the corresponding app are received.

I can try to figure out why this is failing, or alternatively, we can drop this behavior and and just accept whatever happens when you route a request to a service that has nothing backing it.  I wouldn't be surprised if it gives a 503 anyway.

The only reason I was attempting this check to begin with was that v1.x was doing something similar.  It might not be strictly necessary.

**Comment by arschles** [comment]
@krancour I'm in favor of omitting this check and letting it go through, as pods / RCs may come and go during the lifetime of the router in the k8s world

**Comment by mboersma** [comment]
> accept whatever happens when you route a request to a service that has nothing backing it

If that's a 503 or other appropriate error, then +1 for removing our check code and letting k8s do the failing.

**Comment by krancour** [comment]
The router is constantly checking whether annotations have changed or if any annotated service has no endpoints.  So the fact that things can change is accounted for.

I just tested this... sort of:

```
[kent@mbp router]$ k exec -it deis-router-vt9u6 -- bash
bash-4.3# wget http://10.3.0.13:80
Connecting to 10.3.0.13:80 (10.3.0.13:80)
wget: error getting response: Connection reset by peer
```
Can't say I'd be satisfied with that.  A 503 makes more sense.

**Comment by krancour** [comment]
Ok... testing more thoroughly... if I drop this feature of detecting when there are no backend endpoints, and the router sends traffic to the app in question, nginx returns a 502 to the end user.

@mboersma @arschles would you consider that acceptable?

**Comment by arschles** [comment]
ah, right. I missed that it was constantly checking. yes, a 502 is acceptable. maybe create a ticket to investigate a better solution post-alpha?

**Comment by krancour** [comment]
> maybe create a ticket to investigate a better solution post-alpha?

If we think that returning a 502 instead of a 503 is fine, I would just leave it at that.  If we still feel we need a "better solution post-alpha," then it's probably better for me to just fix the array index out of bounds right now.

**Comment by arschles** [comment]
k. I don't think we necessarily need a better solution post-alpha, I assumed the code block that you linked just needed a different way to poll the k8s api though, that's why I suggested the investigatory ticket.

**Comment by mboersma** [comment]
502 seems like an appropriate HTTP response here, so :+1:.
