### ISSUE TITLE
Move some of README into the official docs

### ISSUE THREAD

**Issue by technosophos** [deis/router#61]
Can we move some of the README stuff into the official docs in `deis/workflow`?

**Comment by technosophos** [comment]
Mainly, we need that configuration stuff to go in the appropriate subsection of the documentation. Not in the main installation section. That's already getting way too long.

**Comment by krancour** [comment]
> Can we move some of the README stuff into the official docs in deis/workflow?

We can, but it re-raises the recurring question of how to effectively manage documentation for a component that is reusable on its own _as well as_ relevant docs for the same component within the context of the broader platform.

If these docs _move_, we impair anyone wanting to use this without workflow.  If we _copy_ them, we create a maintenance burden for ourselves.

I'm at a loss.

**Comment by krancour** [comment]
The most crucial bits of router documentation _as it relates to workflow_ have been adapted and added to the workflow docs.  Closing.
