### ISSUE TITLE
Document cloud LoadBalancer tweaks required for router

### ISSUE THREAD

**Issue by slack** [deis/router#64]
Refs deis/workflow#156

We should document the specific timeout requirements for the router component, since many long-running operations are pretty much guaranteed during deploy.

**Comment by krancour** [comment]
I don't disagree.  I think there is already a passing mention of it in the workflow docs.  There are two things to consider...

1. Is this actually a workflow or builder consideration?  They're the things bringing long-running requests to the party.

2.  Whether we document this here or elsewhere, the procedure (or whether it is even necessary) varies by infra.  I think GKE doesn't need this, for instance, while Amazon does, and it's not at all applicable to Vagrant.  In general, how deep do we want to go in documenting all the different underlying stacks?

**Comment by slack** [comment]
We will probably have to document it both places. I filed it here because the router is responsible for service creation which spawns the external load balancer. From a customers perspective, they are most likely interfacing with 'workflow' documentation directly.

For point 2, we'll probably need to strike the balance between how many of the zero-to-kubernetes options we end up documenting. We will get a better sense over time, but I suspect we will routinely doc the sanctioned "local dev environment" along with common deploy platforms like AWS and GKE.
