### ISSUE TITLE
How to do CI with such large dependency graph?

### ISSUE THREAD

**Issue by krancour** [deis/router#7]
Because of this project's dependency on Kubernetes' API, `glide up` (which I have abstracted behind `make bootstrap`) resolves a massive graph of 102 dependencies (most of which are probably not needed).  If running from scratch, this can take 15 minutes.  That's not so bad for a developer.  Even if `glide up` is re-run periodically, in theory, running from _scratch_ is a one-time thing.

But how can we handle this in CI so that tests don't take _forevvvvvvvar_?

Note that this question first popped into my head after looking at this PR:

https://github.com/deis/etcd/pull/11

Ping @mboersma @sgoings @technosophos for thoughts.

**Comment by technosophos** [comment]
I believe we solved this in github.com/helm/helm. You can take a look at the travis file there and see if that helps.

**Comment by krancour** [comment]
@technosophos ah... Travis lets us cache directories.  Cool!  And that was in the other PR I referenced to and I overlooked it.
