### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by krancour** [deis/router#90]
v2 beta requirements include operational metrics from the router.  It's not yet clear what specific metrics are needed.  This issue is just a placeholder for discussion and to ensure we don't lose track of this requirement.

**Comment by jchauncey** [comment]
All the metrics! no seriously all of them. 

This module is obviously a good starting point - https://github.com/vozlt/nginx-module-vts

**Comment by jchauncey** [comment]
* number of status codes (individual and combined) as well as global and per app
* number of current connections (global and per app)
* requests per second (global and per end point)

**Comment by krancour** [comment]
This should be adequately addressed by #106 and #113
